version: "3"

services:
    pg:
        image: bitnami/postgresql
        ports: 
            - 5432:5432
        environment:
            - POSTGRESQL_USERNAME=docker
            - POSTGRESQL_PASSWORD=docker
            - POSTGRESQL_DATABASE=capadura
    redis:
        image: bitnami/redis:latest
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "6379:6379"
